language: r
cache: packages
notifications:
  email:
    false
  webook:
    urls:
      - https://discordapp.com/api/webhooks/371825202578849793/BhZM9dLEygQo7c1a6es-11OiRI115hC4JIPb3g3L2RAbbAXUTghamiJxqCBAwz4M51lg